language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
matrix:
  allow_failures:
    - node_js: "0.11"

install:
  # Install node modules
  - npm install

  # Install gems and sass
  - ruby --version
  - sudo apt-get install rubygems -y
  - sudo gem install sass
  - sass --version

notifications:
  email: false
